#Server
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-exception: false

#Logging
logging:
  level:
    root: INFO
    web: DEBUG
  file:
    name: ./logs/currency-service.log

#Spring
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always

#Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic

#Application settings
app:
  currency:
    base: "USD"
    quote: "RUB"
    deep: 1
  openexchangerates:
    app-id: "31470ef2035043d8b3630f656a12eaf0"
  giphy:
    api-key: "7kRrgXS0IXClkOzHj6Ig4X0yIwT3R9Cy"
